// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ComicHandler is an autogenerated mock type for the ComicHandler type
type ComicHandler struct {
	mock.Mock
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *ComicHandler) Search(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *ComicHandler) Update(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// NewComicHandler creates a new instance of ComicHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComicHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ComicHandler {
	mock := &ComicHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
